WIP: Add travis deploy
insiter/insiter.io pull request #24
Opened 2017-10-11 18:35 UTC by iagodahlem

2017-10-11 18:38 UTC, paulodiovani requested changes
Add a badge to readme too

2017-10-12 16:51 UTC, paulodiovani approved these changes

2017-10-15 23:31 UTC, matheusazzi commented
@iagodahlem is it ready?

2017-10-16 15:01 UTC, paulodiovani requested changes

2017-10-16 15:01 UTC, paulodiovani commented on .travis.yml
> +  - npm install
As discussed on #23, let's use Yarn.

2017-10-16 15:01 UTC, paulodiovani commented on .travis.yml
> +cache: bundler
I think you can add here too:

```yml
cache:
  dirs:
    - node_modules
```

Check documentation for correct syntax

2017-10-16 20:33 UTC, paulodiovani approved these changes
@iagodahlem  We can also make that the `yarn.lock` was updated with `yarn check` command.

2017-10-17 18:39 UTC, iagodahlem commented
@matheusazzi it is not ready yet, but I know what to do now to generate the token. How you are an owner from the organization, could you generate the token for me?

2017-10-17 18:41 UTC, iagodahlem commented
@paulodiovani ok, I will add this check as well.

2017-10-17 18:57 UTC, iagodahlem commented
Token created. Now I think that it's ready to merge.

2017-10-17 19:07 UTC, merged